FROM centos:latest
MAINTAINER Tony Vickers  "lellowconsulting@gmail.com"
ENV REFRESHED_AT 2016-05-05
RUN yum -y install ruby rubygems rubygem-rake
RUN gem install --no-rdoc --no-ri rspec ci_reporter_rspec
